"""Generate .graph.md mermaid diagram files for each example.

Auto-detects @on-decorated handlers by scanning example modules for callables
with the ``_event_types`` attribute (set by the ``@on`` decorator).

Modes:
    Default  — writes/updates files, exits 1 if any changed (for pre-commit).
    --check  — read-only validation, exits 1 if any stale (for tests).
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from types import ModuleType  # noqa: TC003

from langgraph_events import EventGraph

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES_DIR = ROOT / "examples"


def _load_module(path: Path) -> ModuleType:
    """Import a Python file as a module without executing __main__ blocks."""
    name = f"_example_{path.stem}"
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    # Prevent __main__ execution during import
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _find_graph(module: ModuleType) -> EventGraph | None:
    """Return the first module-level ``EventGraph`` instance, if any."""
    for obj in vars(module).values():
        if isinstance(obj, EventGraph):
            return obj
    return None


def _render_graph_md(name: str, mermaid_text: str) -> str:
    """Format the .graph.md content with header and fenced mermaid block."""
    title = name.replace("_", " ").title()
    return (
        f"<!-- Auto-generated by scripts/generate_mermaid.py — do not edit -->\n"
        f"# {title} — Event Flow\n"
        f"\n"
        f"```mermaid\n"
        f"{mermaid_text}\n"
        f"```\n"
    )


def main(check: bool = False) -> int:
    """Iterate examples/*.py, auto-detect handlers, build EventGraph, compare/write.

    Returns 0 if all files are up-to-date, 1 otherwise.
    """
    example_files = sorted(EXAMPLES_DIR.glob("*.py"))
    if not example_files:
        print("No example files found in examples/", file=sys.stderr)
        return 1

    changed = []
    errors = []

    for py_path in example_files:
        graph_md_path = py_path.with_suffix(".graph.md")
        try:
            module = _load_module(py_path)
        except Exception as exc:
            errors.append(f"{py_path.name}: failed to load — {exc}")
            continue

        graph = _find_graph(module)
        if graph is None:
            continue

        mermaid_text = graph.mermaid()
        expected = _render_graph_md(py_path.stem, mermaid_text)

        current = graph_md_path.read_text() if graph_md_path.exists() else ""

        if current != expected:
            if check:
                changed.append(graph_md_path.name)
            else:
                graph_md_path.write_text(expected)
                changed.append(graph_md_path.name)

    if errors:
        for err in errors:
            print(f"ERROR: {err}", file=sys.stderr)

    if changed:
        verb = "stale" if check else "updated"
        print(f"{verb}: {', '.join(changed)}")
        return 1

    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Read-only validation — exit 1 if any file is stale.",
    )
    args = parser.parse_args()
    raise SystemExit(main(check=args.check))
