"""Generate mermaid artifacts for each example and keep docs in sync.

Produces:
- ``examples/<name>.graph.md`` — one per example with both choreography and
  structure views.
- ``docs/patterns.md`` — blocks between ``<!-- autogen:start:<name> -->`` and
  ``<!-- autogen:end -->`` are rewritten per example (hand-authored blurbs
  outside the markers are preserved).
- ``docs/index.md`` — block between ``<!-- autogen:start:hero -->`` and
  ``<!-- autogen:end -->`` gets the ``ddd_order`` unified diagram.

Auto-detects ``@on``-decorated handlers by scanning example modules for any
module-level ``EventGraph`` instance.

Modes:
    Default  — writes/updates files, exits 1 if any changed (for pre-commit).
    --check  — read-only validation, exits 1 if any stale (for tests).
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path
from types import ModuleType  # noqa: TC003

from langgraph_events import EventGraph

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES_DIR = ROOT / "examples"
DOCS_DIR = ROOT / "docs"

PATTERNS_MD = DOCS_DIR / "patterns.md"
INDEX_MD = DOCS_DIR / "index.md"

GITHUB_EXAMPLES_URL = (
    "https://github.com/cadance-io/langgraph-events/blob/main/examples"
)

HERO_EXAMPLE = "ddd_order"

# Legend rendered as a live mermaid "vocabulary diagram" — every shape
# and edge kind in use on the real per-example diagrams.  Works on
# GitHub (renders markdown + mermaid inside <details> natively) and on
# MkDocs + md_in_html (the `markdown="1"` attribute opts the block into
# markdown parsing inside Python-Markdown).
# Long-line-avoidance: compose the halt classdef via implicit string
# concatenation so every physical source line stays inside the 88-column
# budget while the runtime string keeps the single-line mermaid syntax.
_HALT_CLASSDEF = (
    "    classDef halt "
    "fill:#fef3c7,stroke:#b45309,color:#78350f,"
    "stroke-width:3px,stroke-dasharray:4 2"
)

_LEGEND_BLOCK = f"""<details markdown="1">
<summary>🗝️ Diagram vocabulary</summary>

```mermaid
graph LR
    classDef entry fill:none,stroke:none,color:none
    classDef cmd fill:#dbeafe,stroke:#1d4ed8,color:#1e3a8a
    classDef devt fill:#dcfce7,stroke:#15803d,color:#14532d
    classDef intg fill:#ede9fe,stroke:#6d28d9,color:#4c1d95
    classDef syst fill:#fef3c7,stroke:#b45309,color:#78350f
{_HALT_CLASSDEF}
    classDef inv fill:#ffedd5,stroke:#c2410c,color:#7c2d12
    subgraph Example["Aggregate"]
      direction LR
      Command{{{{Command}}}}:::cmd
      DomainEvent(DomainEvent):::devt
      Halted([Halted]):::halt
      Invariant{{Invariant}}:::inv
    end
    IntegrationEvent[/IntegrationEvent/]:::intg
    SystemEvent([SystemEvent]):::syst
    _seed_[ ]:::entry ==> Command
    Command -->|handler| DomainEvent
    Command -.->|"handler (raises)"| SystemEvent
    Command -.->|scatter| IntegrationEvent
    Command -.- Halted
    Command -.->|invariant| Invariant
    linkStyle 1 stroke:#6b7280,stroke-dasharray:3 3
    linkStyle 2 stroke:#7c3aed,stroke-width:2.5px,stroke-dasharray:8 3
    linkStyle 3 stroke:#9ca3af,stroke-dasharray:3 3
    linkStyle 5 stroke:#c2410c,stroke-dasharray:4 2
```

</details>"""


def _load_module(path: Path) -> ModuleType:
    """Import a Python file as a module without executing __main__ blocks."""
    name = f"_example_{path.stem}"
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    # Prevent __main__ execution during import
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _find_graph(module: ModuleType) -> EventGraph | None:
    """Return the first module-level ``EventGraph`` instance, if any."""
    for obj in vars(module).values():
        if isinstance(obj, EventGraph):
            return obj
    return None


def _indent(body: str, spaces: int = 4) -> str:
    """Indent every line of *body* by *spaces* — required for tab bodies."""
    pad = " " * spaces
    return "\n".join(pad + line if line else line for line in body.split("\n"))


def _render_graph_md(name: str, renders: dict[str, str]) -> str:
    """Format the .graph.md content — two views as h2 sections so GitHub
    (which doesn't support pymdownx.tabbed) still renders it usefully."""
    title = name.replace("_", " ").title()
    return (
        f"<!-- Auto-generated by scripts/generate_mermaid.py — do not edit -->\n"
        f"# {title}\n"
        f"\n"
        f"{_LEGEND_BLOCK}\n"
        f"\n"
        f"## Diagram\n"
        f"\n"
        f"Event flow via command handlers and policies, with dashed "
        f"ownership arrows filling in declared outcomes that no handler "
        f"produces directly.\n"
        f"\n"
        f"```mermaid\n"
        f"{renders['mermaid_choreography']}\n"
        f"```\n"
        f"\n"
        f"## Choreography (text)\n"
        f"\n"
        f"```text\n"
        f"{renders['text_choreography']}\n"
        f"```\n"
    )


def _render_patterns_block(name: str, renders: dict[str, str]) -> str:
    """Tabbed block inserted under each example in patterns.md.

    Two tabs: Diagram / Flow (text). Content inside a ``=== "Tab"`` block
    must be indented 4 spaces, or pymdownx.tabbed silently drops it.
    """
    mermaid_chor = _indent(f"```mermaid\n{renders['mermaid_choreography']}\n```")
    text_chor = _indent(f"```text\n{renders['text_choreography']}\n```")
    return (
        f'=== "Diagram"\n\n{mermaid_chor}\n\n'
        f'=== "Flow (text)"\n\n{text_chor}\n\n'
        f"[Full code]({GITHUB_EXAMPLES_URL}/{name}.py) · "
        f"[Raw diagrams on GitHub]({GITHUB_EXAMPLES_URL}/{name}.graph.md)"
    )


def _rewrite_autogen_block(content: str, marker: str, body: str) -> str:
    """Replace the block between ``<!-- autogen:start:<marker> -->`` and
    ``<!-- autogen:end -->`` with *body*. Returns the full file content.

    The body match is anchored on the start marker and terminated by the
    *first* ``<!-- autogen:end -->`` that is not preceded by another
    ``<!-- autogen:`` token — so adjacent autogen blocks can't accidentally
    get merged when one has an empty body.
    """
    pattern = re.compile(
        rf"(<!-- autogen:start:{re.escape(marker)} -->)"
        r"((?:(?!<!-- autogen:).)*)"
        r"(<!-- autogen:end -->)",
        re.DOTALL,
    )
    replacement = rf"\g<1>\n{body}\n\g<3>"
    return pattern.sub(replacement, content, count=1)


def _build_example_renders(
    examples: list[tuple[Path, EventGraph]],
) -> dict[str, dict[str, str]]:
    """Return two ``domain()`` renders per example, keyed by stem.

    One unified mermaid diagram (flow + ownership-gap fill), plus the
    choreography text view for quick reference.
    """
    out: dict[str, dict[str, str]] = {}
    for py_path, graph in examples:
        model = graph.domain()
        out[py_path.stem] = {
            "mermaid_choreography": model.mermaid(),
            "text_choreography": model.text(view="choreography"),
        }
    return out


def _sync_graph_md(py_path: Path, renders: dict[str, str], check: bool) -> str | None:
    """Write/compare the example's ``.graph.md``. Returns filename if changed."""
    graph_md_path = py_path.with_suffix(".graph.md")
    expected = _render_graph_md(py_path.stem, renders)
    current = graph_md_path.read_text() if graph_md_path.exists() else ""
    if current == expected:
        return None
    if not check:
        graph_md_path.write_text(expected)
    return graph_md_path.name


def _sync_patterns_md(
    renders_by_stem: dict[str, dict[str, str]], check: bool
) -> str | None:
    """Rewrite autogen blocks in docs/patterns.md. Returns filename if changed."""
    if not PATTERNS_MD.exists():
        return None
    original = PATTERNS_MD.read_text()
    updated = original
    for stem, renders in renders_by_stem.items():
        updated = _rewrite_autogen_block(
            updated, stem, _render_patterns_block(stem, renders)
        )
    if updated == original:
        return None
    if not check:
        PATTERNS_MD.write_text(updated)
    return PATTERNS_MD.name


def _sync_single_block(path: Path, marker: str, body: str, check: bool) -> str | None:
    """Rewrite one autogen block in *path*. Returns filename if changed."""
    if not path.exists():
        return None
    original = path.read_text()
    updated = _rewrite_autogen_block(original, marker, body)
    if updated == original:
        return None
    if not check:
        path.write_text(updated)
    return path.name


def main(check: bool = False) -> int:  # noqa: PLR0912
    """Regenerate all mermaid artifacts. Returns 0 if all current, 1 otherwise."""
    example_files = sorted(EXAMPLES_DIR.glob("*.py"))
    if not example_files:
        print("No example files found in examples/", file=sys.stderr)
        return 1

    errors: list[str] = []
    examples: list[tuple[Path, EventGraph]] = []

    for py_path in example_files:
        try:
            module = _load_module(py_path)
        except Exception as exc:
            errors.append(f"{py_path.name}: failed to load — {exc}")
            continue
        graph = _find_graph(module)
        if graph is None:
            continue
        examples.append((py_path, graph))

    renders_by_stem = _build_example_renders(examples)

    changed: list[str] = []
    for py_path, _graph in examples:
        changed_name = _sync_graph_md(py_path, renders_by_stem[py_path.stem], check)
        if changed_name is not None:
            changed.append(changed_name)

    # docs/patterns.md — one-shot legend block near the top.
    legend_changed = _sync_single_block(PATTERNS_MD, "legend", _LEGEND_BLOCK, check)
    if legend_changed is not None:
        changed.append(legend_changed)

    # docs/patterns.md — autogen blocks per example.
    patterns_changed = _sync_patterns_md(renders_by_stem, check)
    if patterns_changed is not None and patterns_changed not in changed:
        changed.append(patterns_changed)

    # docs/index.md — hero choreography block.
    if HERO_EXAMPLE in renders_by_stem:
        hero_body = (
            f"```mermaid\n{renders_by_stem[HERO_EXAMPLE]['mermaid_choreography']}\n```"
        )
        index_changed = _sync_single_block(INDEX_MD, "hero", hero_body, check)
        if index_changed is not None:
            changed.append(index_changed)

    if errors:
        for err in errors:
            print(f"ERROR: {err}", file=sys.stderr)

    if changed:
        verb = "stale" if check else "updated"
        print(f"{verb}: {', '.join(changed)}")
        return 1

    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Read-only validation — exit 1 if any file is stale.",
    )
    args = parser.parse_args()
    raise SystemExit(main(check=args.check))
